### ISSUE TITLE
Append note to task field

### ISSUE THREAD

**Issue by robdecker** [chapter-three/teamwork-log#2]
Append the Tyme `notes` field to the `task` field to be used in Teamwork's `description` field. For example, if my task is `Build` and my note is `create news and assoc views`, output should be something to:

`Build: create news and assoc views`

**Comment by moonray** [comment]
Do you start/stop the task multiple times? If so, do you attach different notes to each entry?
log merges all entries for a task into one time entry to log into teamwork. Not sure how it should work with multiple notes.

**Comment by robdecker** [comment]
I do start/stop a task multiple times. Sometimes it'll have the same note,
and other times it will not.

Instead of combining based only on the task, perhaps you could combine on
the task/note pair?

**Comment by robdecker** [comment]
Works great!
